---
- name: "Instala o Apache em distro drivadas do Debian"
  apt:
    name:
      - apache2
      - libapache2-mod-fcgid
      - libapache2-mod-security2
      - libapache2-mod-evasive
      - openssl
    state: latest
  when: (ansible_facts['distribution'] == "Debian")
  notify:
  - enableApache2

- name: "Habilita mods no apache2 - Debian"
  apache2_module:
    name: "{{ item }}"
  with_items:
    - actions
    - fcgid
    - alias
    - proxy_fcgi
    - headers
    - ssl
  when: (ansible_facts['distribution'] == "Debian")

- name: "Cria virtual host com as configurações do site - Debian "
  template:
      src: templates/site.conf
      dest: /etc/apache2/sites-available/{{ log_prefix }}.conf
  when: (ansible_facts['distribution'] == "Debian")
  notify:
    - enableSite
    - reloadApache2
    - addInHostsFile 
    - InstallWordPress
    - SetPermissionWp-Debian
