---
# handlers file for servertools
- name: "AddInHostsFile"
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items: 
    - "127.0.0.1 {{ hostname }}"
    - "{{ inventory_hostname }} {{ hostname }}"

- name: "Restart-Server"
  reboot:

- name: "Enable-Yum-Utils"
  shell:
    cmd: "yum-config-manager --enable remi-php74"
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribuition_major_version'] == "7"   
